version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5433"
    env_file:
      - .env
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
      - ./postgres/dump/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOST}

  # react-app:
  #   build: ./frontend/web-app
  #   container_name: react-app
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true

  backend:
    build: ./backend
    container_name: nestjs-app
    volumes:
      - ./backend/:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env

  minio-server:
    container_name: minio-server
    image: minio/minio
    restart: always
    volumes:
      - ./volumes/minio:/data
    environment:
      #      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      #      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL} # web app address
      #      MINIO_SERVER_URL: ${MINIO_SERVER_URL} # address for static files 'https://static.domain.me'
      MINIO_PORT: ${MINIO_MAIN_PORT_IN}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_MAIN_PORT_OUT}:${MINIO_MAIN_PORT_IN}
      - ${MINIO_CONSOLE_PORT_OUT}:${MINIO_CONSOLE_PORT_IN}
    command: server --address ":${MINIO_MAIN_PORT_IN}" --console-address ":${MINIO_CONSOLE_PORT_IN}" /data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${MINIO_CONSOLE_PORT_OUT}/minio/health/live",
        ]
      interval: 10s
      timeout: 10s
      retries: 30
